apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demoabc-gitops
  description: This is GitOps manifest for demoabc   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: demoabc
    janus-idp.io/tekton: demoabc 
    backstage.io/kubernetes-id: demoabc
    backstage.io/kubernetes-namespace: demo2
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:demoabc
