apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: demoabc
  janus-idp.io/tekton: demoabc
  backstage.io/kubernetes-id: demoabc
  backstage.io/kubernetes-namespace: demo2 
  app.kubernetes.io/part-of: demoabc
resources: 
- deployment.yaml
- route.yaml
- service.yaml
- combined.yaml
- topic.yaml
